### ISSUE TITLE
ngx-widget-grid soving render2 issue

### ISSUE THREAD

**Issue by kirtiesl** [envyN/ngx-widget-grid#1]
I am getting following issue while implementing ngx-widget-grid with angular 2.4.3. Is this version compatiblity issue?? Please Help.
ngx-widget-grid/dist/components/grid/grid.component.js
223:12-21 "export 'Renderer2' was not found in '@angular/core'

**Comment by envyN** [comment]
Hi @kirtiesl ,
Since version 2.0.0 the library works with Angular 4,
In case you wish to use it with Angular 2.x, please use 1.7 as a dependency though i would suggest you upgrade to Angular 4.x if possible since that has been released in April'17

**Comment by kirtiesl** [comment]
thank you.
