### ISSUE TITLE
TRASH Icon not clickable

### ISSUE THREAD

**Issue by dgodard** [envyN/ngx-widget-grid#17]
**Select one ...**  (check one with "x")
   ```
   [x] bug
   [ ] feature request
   [ ] enhancement
   ```
   
   ### Expected behavior
Click on trash delete the widget
   
   ### Actual behavior
 Because of mover div on top of the div stack, we can't click on trash icon in the underlaying div  :
  
   ### Reproduction of behavior
   Reproducible online on the basic sample : https://envyn.github.io/ngx-widget-grid/#/basic
   Go to edit mode, trash are displayed inside the widget. But you can't click them.
   ### Environment details
   
  
   
   * **Browser:** [all | Chrome XX | Firefox XX | IE XX]

**Comment by ptretyakov** [comment]
I have set z-index to 21 on the button and it's all okey.

**Comment by Joooooooooogi** [comment]
I'm currently struggeling with the same issue - on editable, none of the content is accessible. Even incrementing the z-index doesn't work for me. Has anybody figured out a solution so far?

**Comment by envyN** [comment]
The online demo is half baked right now. And yes, you'll need to tweak the z-index a bit to get the icons to be clickable.
I'll probably find some time over the next 10 days to clean up the demo a little bit.
