### ISSUE TITLE
Dom elements other than the grid widgets loose drag-features if resizable is set to true

### ISSUE THREAD

**Issue by Draftscode** [envyN/ngx-widget-grid#3]
I tested with the demo page: I set the header-elements directive to "draggable='true'" just for testing the drag features. But if there is a widget inside of the grid and [resizeable] is true, I cannot drag the header-element anymore until I remove that widget.

**Comment by envyN** [comment]
@Draftscode let me understand this a bit better, 
are you trying to drag and drop from another component outside of the widget-grid area into the grid?
If yes, then I must say that I have not tried that out yet.
Drag and resizing works for widgets already added to the grid.
And addition of widgets is through a callback (mostly a click callback on a button outside the grid)

In any case, if you can reproduce your problem on a plnkr, i can investigate further.

**Comment by envyN** [comment]
@Draftscode pls fork [http://plnkr.co/pvA8jx](http://plnkr.co/pvA8jx) and update with your changes so that the issue can be investgated fuurther.

**Comment by Draftscode** [comment]
Made some changes to your plnkr: http://plnkr.co/edit/pWDcFbujOGE0MDJjOZST
Have fun

**Comment by Draftscode** [comment]
Made some changes to your plnkr: http://plnkr.co/edit/pWDcFbujOGE0MDJjOZST
Have fun
 

Gesendet: Montag, 18. September 2017 um 16:50 Uhr
Von: "Naveen Adarsh" <notifications@github.com>
An: envyN/ngx-widget-grid <ngx-widget-grid@noreply.github.com>
Cc: Draftscode <sebastian.rupprecht@gmx.de>, Mention <mention@noreply.github.com>
Betreff: Re: [envyN/ngx-widget-grid] document looses drag-features (#3)


@Draftscode pls fork http://plnkr.co/pvA8jx and update with your changes so that the issue can be investgated fuurther.

**Comment by envyN** [comment]
@Draftscode Please check the plnkr [http://plnkr.co/edit/KXSaDCrCE7UfJcGvQuDL?p=preview](http://plnkr.co/edit/KXSaDCrCE7UfJcGvQuDL?p=preview).
Seems to have solved the problem with 2.0.3
Please reopen if you find the issue again.
🥂

**Comment by Draftscode** [comment]
@envyN Looks fine. Thanks for your efforts.
