### ISSUE TITLE
Concept of colspan and rowspan

### ISSUE THREAD

**Issue by beeing** [envyN/ngx-widget-grid#7]
**Select one ...**  (check one with "x")
   ```
   [ ] bug
   [x] feature request
   [ ] enhancement
   ```
   
   ### Expected behavior

Similar to HTML tables, it is possible to span across multiple columns or rows. This is particularly useful for widgets that can stretch horizontally or vertically.

For those who do not prefer to have a scrollbar within each widget, this will provide a nicer UX.

**Comment by envyN** [comment]
Hi @beeing, Widget resizing is already a feature. Did you try something like this:
```
<ngx-widget [resizable]="true" [(position)]="widget.position"...>
```
That should allow you to shrink/expand widgets

**Comment by beeing** [comment]
Maybe that's possible, will try it out first. Thanks.
